name: Sync From Git To Azure
on: 
  push:
    branches:
      - '*'
      #- '!master' # This line is used to restrict this pipeline which won't triggers 
    
jobs:
  sync_from_git_to_azure:
    runs-on: ubuntu-latest
    environment: AZUREPAT
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment variables
      run: |   
      env:
        AZUREPAT: ${{secrets.AZUREPAT}} # calling secrets from environment variables
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
    - name: Git clone repo
      run: |
        git clone https://github.com/dariemcarlosdev/eHandbookApp.git
        cd eHandbookApp
        rm -rf .git
    - name: Clone to Azure DevOps Repo
      run: |
        cd ..
        GIT_CMD_REPOSITORY="https://335286:qv2zagvubsovsyioeuzn335qx6owgmlvsqt4awrplmwmbdy57zfq@dev.azure.com/MDPCS/eHandBook/_git/eHandbookAppa" 
        git clone $GIT_CMD_REPOSITORY
    - name: Copy files from git repro to azure repro
      run: |
        cp -r eHandbookAppa/* eHandbookApp/
    - name: Configure user in azure repro
      run: |
        cd eHandbookApp
        git config --global user.email "$AZUSER_EMAIL"
        git config --global user.name "$AZUSERNAME"
    - name: Commit and Push to azure
      run: |
        git add .
        git commit -m "sync from git to azure"
        git push
