name: Push directory to another azure repository
on:
  push:
    branches:
      - '*' # applies for all branches in github.
      - '!master' # This line is used to restrict this pipeline which won't triggers for master branch. remove this if you need to trigger for code push in master branch (Create PR if needed in devops repos)
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: AZUREPAT
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{vars.AZUREPAT}} # calling secrets from environment variables
        AZUSERNAME: ${{vars.AZUSERNAME}}
        AZUSER_EMAIL: ${{vars.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
      run: |
         chmod +x ./commit.sh
         ./commit.sh # it will calls 'commit.sh' file. Thats where our logic is in.
      shell: bash
